name: nettruyen_reader
description: A polished, ad-free comic reading experience for NetTruyen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  photo_view: ^0.14.0
  shimmer: ^2.0.0
  flutter_inappwebview: ^6.1.5
  flutter_cache_manager: ^3.4.1
  visibility_detector: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
